### PR TITLE
Issue of header not showing and made complete website mobile responsive

### PR DESCRIPTION
**Pull request by vinodselvin**
#37 Make Mobile Responsive

### CODE REVIEW

**Comment by championshuttler** [comment]
Can you please share your github.io link or screenshot :) @vinodselvin

**Comment by vinodselvin** [comment]
https://vinodselvin.github.io/hacktoberfest/index.html

**Comment by vinodselvin** [comment]
Have you checked the link? https://vinodselvin.github.io/hacktoberfest/index.html

**Comment by championshuttler** [comment]
@vinodselvin  Awesome work :)

**Comment by championshuttler** [comment]
@chocos10 see :D

**Comment by vinodselvin** [comment]
Nice :)

**Pull request merged**
