### PR TITLE
improved the footer and added hacktoberfest logo

### PR DESCRIPTION
**Pull request by GeekyShacklebolt**
Have improved the footer a bit and added the hacktoberfest logo pic.

### CODE REVIEW

**Comment by GeekyShacklebolt** [comment]
I have added Css file to make the site more attractive whose screenshot is attached
here

**Comment by championshuttler** [comment]
use new logo please its a old one

**Comment by GeekyShacklebolt** [comment]
the footer in my PR is shown here. 
footer_changed

**Comment by GeekyShacklebolt** [comment]
after adding the logo the webpage is looking like this
hacktoberfest_logo_added

**Pull request merged**
