### PR TITLE
styling and improvingFooter madic00

### PR DESCRIPTION
**Pull request by alemadic**
styling and improvingFooter

### CODE REVIEW

**Comment by suhailsinghbains** [comment]
Thanks for the PR, great work, the links and styling are perfect, couple of things before I could merge this:
1. Edit [this](https://github.com/Moz-NIEC/hacktoberfest/pull/69#issue-220012822) and add "Fixes #32 " into the comment made by @madic00 .
2. Include a screenshot so that it is easy for us & others to see the changes made. A before and after screenshots would be a nice touch.

**Comment by alemadic** [comment]
Fixes #32 
capture

**Comment by suhailsinghbains** [comment]
LGTM
Thanks for the work done, really appreciate it. Please make sure that, your 1st comment has the phrase "Fixes #IssueNumber" from next time :) .
Anyway, thanks !

**Comment by alemadic** [comment]
Thanks for advice, I am new in world of open source and I am proud that
complete the chellenge now

**Pull request merged**
